FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY --from=builder /app/dist ./dist

# Create a symbolic link for the @ alias
RUN ln -s /app/dist /app/@

EXPOSE 4001

CMD ["node", "-r", "module-alias/register", "dist/app.js"]
